### ISSUE TITLE
Support terminal light theme

### ISSUE THREAD

**Issue by surban** [pythops/bluetui#10]
Very nice work!

My only issue is that, when my terminal (GNOME terminal) is set to light mode, the UI becomes unreadable due to inappropriate colors.

![image](https://github.com/pythops/bluetui/assets/1213857/8f43b170-95bd-4bbb-b95c-0dfbb9487f30)

Would it be possible to detect the terminal color scheme and adapt accordingly?

**Comment by pythops** [comment]
Thanks
Definitely :100:

**Comment by pythops** [comment]
I made the necessary changes in #11 , let me know if those colors work for you

**Comment by surban** [comment]
Thanks, looks good!

**Comment by aljustiet** [comment]
The same issue on foot and ghostty terminals.
