### ISSUE TITLE
ERROR: Could not activite remote peer 'org.bluez'

### ISSUE THREAD

**Issue by joksdz** [pythops/bluetui#17]
am running on arch v 6.9.2 with hyprland 
i have bluez and bluez-utils at the latest version 

am getting an error when trying to run : 

`Error: Error { kind: Internal(DBus("org.freedesktop.DBus.Error.NameHasNoOwner")), message: "Could not activate remote peer 'org.bluez': activation request failed: unknown unit" }`
am not really good with rust,thank you for understanding.

**Comment by pythops** [comment]
do you have the service `bluetooth.service` running ?

**Comment by joksdz** [comment]
i just figured that out ,thx any ways
