### ISSUE TITLE
Package for NixOS

### ISSUE THREAD

**Issue by sakshatshinde** [pythops/bluetui#19]
Consider packaging this for NixOS https://pavluk.org/blog/2023/05/30/nix_packaging.html

**Comment by pythops** [comment]
I can look at it later, but you can send a PR meanwhile, that would be great :pray:

**Comment by sakshatshinde** [comment]
I've never packaged any software (might take a shot at it) in the meantime ~ if anyone wants they can have a go at it https://nix.dev/tutorials/packaging-existing-software.html

**Comment by Samuel-Martineau** [comment]
@sakshatshinde Is #21 what you had in mind?

**Comment by alexandru0-dev** [comment]
@Samuel-Martineau great job, a flake is really good.
In the future can also be upstream as only some little modifications are needed

**Comment by Samuel-Martineau** [comment]
@alexandru0-dev I was thinking of submitting a nixpkgs PR in the the next few weeks. I started with a flake because adding new packages to nixpkgs can be a very slow process.

**Comment by alexandru0-dev** [comment]
@Samuel-Martineau ik, fully agree.
Also a flake let's you be at git version vs a release which nix (most of the time) uses

**Comment by donovanglover** [comment]
@Samuel-Martineau Thanks for packaging this! If you make a PR I can help merge bluetui into nixpkgs. Make sure to follow the format in the [nixpkgs manual](https://nixos.org/manual/nixpkgs/unstable/#compiling-rust-applications-with-cargo).

- Set `meta.mainProgram` to `"bluetui"`
- Replace `repo = pname;` with `repo = "bluetui";`
- Set `meta.platforms` to `lib.platforms.linux`

**Comment by ArtemChandragupta** [comment]
Hi. How is the nixpkg progress?

**Comment by donovanglover** [comment]
@ArtemChandragupta I made a PR here: https://github.com/NixOS/nixpkgs/pull/348939
