### ISSUE TITLE
Handle rfkill softblock

### ISSUE THREAD

**Issue by 766F6964** [pythops/bluetui#20]
**Summary:**
When attempting to start `bluetui` and Bluetooth is soft-blocked as indicated by rfkill, `bluetui` fails to start without any notifications. The terminal remains empty, no UI appears, and no error messages are displayed to the user. I think, it in this case, it would make sense to inform the user to unblock Bluetooth before starting `bluetui`.

**Comment by pythops** [comment]
Good one yes :100:

**Comment by pythops** [comment]
Done
