### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by LionyxML** [pythops/bluetui#23]
Thanks for this awesome package!

Is there a way to configure some bluetooth settings specific for the device? 

Like, on my headphones on gui (blueman-manager) I can set the mode it is working, like AD2P, HSP/HFP and also choose the codecs.

**Comment by pythops** [comment]
I personally do not know that deep in the Bluetooth world but maybe this is the opportunity to do it :sweat_smile: 
I can look at for sure. Meanwhile, if someone out there knows already how to do it, plz go for it.

**Comment by treeshateorcs** [comment]
i use pulsemixer for that

**Comment by LionyxML** [comment]
Thanks @treeshateorcs!

This actually solves the problem of having "bluetooth and sound controls" all on CLI.

@pythops: As a log note for further reference:

On pulsemixer use F3, select the bluetooth device, hit enter:

<img width="1017" alt="Captura de Tela 2024-09-13 às 22 23 07" src="https://github.com/user-attachments/assets/32693b70-c8d8-4c04-b8e5-b95657e12ab3">

Select the profile:

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/21bb620d-7219-4cc9-88ce-b233a21d95a0">

And that's it! :)
