### ISSUE TITLE
nothing is shown after installing "bluetui"

### ISSUE THREAD

**Issue by evanescente-ondine** [pythops/bluetui#24]
Hi.
I installed bluetui with cargo, and I see literally nothing, a blank terminal window.
![image](https://github.com/user-attachments/assets/155dbb36-3360-4b8b-8eb7-89b8b9ce80fa)

bluetui 0.5.1
Linux 84-47-09-37-40-35 6.9.11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.9.11-1 (2024-07-25) x86_64 GNU/Linux

**Comment by pythops** [comment]
can you check if `bluetooth` service is running.
```
systemctl status bluetooth
```
if not, you can start it
```
sudo systemctl start bluetooth
```

Let me know how it goes for you :)

**Comment by evanescente-ondine** [comment]
Oh, huh, that's what it means... Sorry.
Works fine, I love not needing  those infinite kde or gnome dependencies !
Thanks a lot, plus TUI in general rock !!

**Comment by pythops** [comment]
you're welcome, glad you like it :)
