### ISSUE TITLE
[Feature Request] Change order of adapter and devices

### ISSUE THREAD

**Issue by cvanelteren** [pythops/bluetui#26]
I find most my time just activating a connection which requires the additional tab press. Having the selected cell or even flipping the devices to the top would be greatly appreciated.

Thanks for the amazing tool!

**Comment by pythops** [comment]
:thinking: not bad actually yeah

**Comment by cvanelteren** [comment]
Not too familiar with rust, but browsing through the code I seems doable. There is no config file being use that you could specify the layout is there?

**Comment by pythops** [comment]
I am working on it and I am taking the opportunity to do some refactoring as well. expect to be merged by the next week

**Comment by sermuns** [comment]
Great tool! I was wondering, how is this feature implemented? I cannot find it anywhere.
