### ISSUE TITLE
Center the UI

### ISSUE THREAD

**Issue by orhun** [pythops/bluetui#3]
On my terminal `bluetui` looks like this:

![image](https://github.com/pythops/bluetui/assets/24392180/1956c7b4-51dc-43c4-a40a-f6209b6c8bf1)

I think it would be nice to vertically center the widgets to make things more symmetric.

What do you think?

**Comment by pythops** [comment]
I agree that it would be better with some symmetric layout. 
What layout do you suggest knowing that there is another block that appears when scanning for a new devices ?

**Comment by orhun** [comment]
You can shift everything upwards when there is a new block and keep everything centered 🐻

**Comment by pythops** [comment]
If you can send a PR for it, sure :)

**Comment by orhun** [comment]
I made the changes:

![image](https://github.com/pythops/bluetui/assets/24392180/b17340c8-5552-48ba-ba1c-17a65dcc2af9)

What do you think of this? It still feels a bit odd to me. I'm wondering what's missing.

**Comment by orhun** [comment]
I think fixed percentages are better (%33 for each block):

![image](https://github.com/pythops/bluetui/assets/24392180/5c81c962-7815-436b-ae2c-b9b5713bd3fd)

**Comment by pythops** [comment]
Yeah I like the last one with fixed percentages better.
