### ISSUE TITLE
Highlighted item is invisible with Solarized light theme

### ISSUE THREAD

**Issue by matejdro** [pythops/bluetui#30]
With Solarized Light terminal theme, text of the highlighted item is invisible (see first item under paired devices):

![image](https://github.com/user-attachments/assets/280f2d69-064c-402a-a4ea-306c95c84a46)

Theme:

![image](https://github.com/user-attachments/assets/221301ef-15a4-4f96-b7f4-57728346842e)

**Comment by pythops** [comment]
This PR https://github.com/pythops/bluetui/pull/32 should fix it
Can you plz check ?

**Comment by mattkang** [comment]
@pythops was coming to report the same issue on `0.5.1`.  I was using everforest, and it was only an issue in the scanning pane for me.

**Fixed for me now, thanks!**
![before](https://github.com/user-attachments/assets/1d2ee7b3-c606-4eb9-9a72-2c0469888289)
![after](https://github.com/user-attachments/assets/2aed06f8-ae26-4dd9-867a-1b8d3101d866)

**Comment by matejdro** [comment]
Also can confirm it works from my side. Thanks a lot!

Any chance for a release with this fix?

**Comment by pythops** [comment]
Hopefully by the end of the week or this weekend the latest

**Comment by pythops** [comment]
@matejdro releaed now, enjoy

**Comment by matejdro** [comment]
Can confirm, also fixed in release version. Thanks!
