### ISSUE TITLE
Feature: bundle a desktop file entry

### ISSUE THREAD

**Issue by izmyname** [pythops/bluetui#38]
It would be nice to have a `.desktop` file entry bundled, for desktop integration.

**Comment by pythops** [comment]
PRs are always welcome :)

**Comment by izmyname** [comment]
Alas, I'm unfamiliar with cargo and rust

**Comment by pythops** [comment]
maybe someone else can do it from the community :) 
I'll let this open just in case

**Comment by UnaTried** [comment]
#41

**Comment by pythops** [comment]
I think I have to reject this sorry. `bluetui` is a cli that should be run from terminal. If someone wants to use it as desktop icon, fine, they can search on how to do it.
